/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (ape-escape-)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800A3660u
#define func_800A3660 BootEntry  /* alias */
